"""initial schema

Revision ID: 11dcefc5c1a0
Revises:
Create Date: 2026-07-13 03:31:59.456517

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "11dcefc5c1a0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("site_code", sa.String(length=50), nullable=False),
        sa.Column("profile_image_url", sa.String(length=500), nullable=True),
        sa.Column("platform", sa.String(length=20), nullable=True),
        sa.Column("push_token", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_site_code"), ["site_code"], unique=False)

    op.create_table(
        "found_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("site_code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=30), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("found_at", sa.DateTime(), nullable=False),
        sa.Column("storage_location", sa.String(length=100), nullable=False),
        sa.Column("features", sa.Text(), nullable=False),
        sa.Column("private_feature", sa.Text(), nullable=True),
        sa.Column("verification_question", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("found_posts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_found_post_match_candidates",
            ["site_code", "status", "category", "found_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_found_posts_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_found_posts_color"), ["color"], unique=False)
        batch_op.create_index(batch_op.f("ix_found_posts_found_at"), ["found_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_found_posts_location"), ["location"], unique=False)
        batch_op.create_index(batch_op.f("ix_found_posts_site_code"), ["site_code"], unique=False)
        batch_op.create_index(batch_op.f("ix_found_posts_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_found_posts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "lost_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("site_code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=30), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("lost_at", sa.DateTime(), nullable=False),
        sa.Column("features", sa.Text(), nullable=False),
        sa.Column("private_feature", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("contact_method", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lost_posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lost_posts_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_lost_posts_color"), ["color"], unique=False)
        batch_op.create_index(batch_op.f("ix_lost_posts_location"), ["location"], unique=False)
        batch_op.create_index(batch_op.f("ix_lost_posts_lost_at"), ["lost_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_lost_posts_site_code"), ["site_code"], unique=False)
        batch_op.create_index(batch_op.f("ix_lost_posts_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_lost_posts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lost_post_id", sa.Integer(), nullable=False),
        sa.Column("found_post_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("category_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("color_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("location_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("time_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("feature_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("claim_answer", sa.Text(), nullable=True),
        sa.Column("claim_message", sa.String(length=500), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_by", sa.Integer(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("handed_over_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["found_post_id"],
            ["found_posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lost_post_id"],
            ["lost_posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lost_post_id", "found_post_id", name="uq_match_pair"),
    )
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_matches_found_post_id"), ["found_post_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_matches_lost_post_id"), ["lost_post_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_matches_score"), ["score"], unique=False)
        batch_op.create_index(batch_op.f("ix_matches_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_matches_status"))
        batch_op.drop_index(batch_op.f("ix_matches_score"))
        batch_op.drop_index(batch_op.f("ix_matches_lost_post_id"))
        batch_op.drop_index(batch_op.f("ix_matches_found_post_id"))

    op.drop_table("matches")
    with op.batch_alter_table("lost_posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lost_posts_user_id"))
        batch_op.drop_index(batch_op.f("ix_lost_posts_status"))
        batch_op.drop_index(batch_op.f("ix_lost_posts_site_code"))
        batch_op.drop_index(batch_op.f("ix_lost_posts_lost_at"))
        batch_op.drop_index(batch_op.f("ix_lost_posts_location"))
        batch_op.drop_index(batch_op.f("ix_lost_posts_color"))
        batch_op.drop_index(batch_op.f("ix_lost_posts_category"))

    op.drop_table("lost_posts")
    with op.batch_alter_table("found_posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_found_posts_user_id"))
        batch_op.drop_index(batch_op.f("ix_found_posts_status"))
        batch_op.drop_index(batch_op.f("ix_found_posts_site_code"))
        batch_op.drop_index(batch_op.f("ix_found_posts_location"))
        batch_op.drop_index(batch_op.f("ix_found_posts_found_at"))
        batch_op.drop_index(batch_op.f("ix_found_posts_color"))
        batch_op.drop_index(batch_op.f("ix_found_posts_category"))
        batch_op.drop_index("ix_found_post_match_candidates")

    op.drop_table("found_posts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_site_code"))
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
